---

name: Build Container

on: 
  push: 
    branches: 
      - main


jobs:
  SWListMaker: 
    runs-on: "windows-2019"

    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Download JSON
        run: |
          cd SWListMaker
          echo
          echo "Downloading latest json files"
          mkdir cardlists\\JSON
          Invoke-WebRequest https://raw.githubusercontent.com/swccgpc/swccg-card-json/main/Dark.json -Outfile cardlists\\JSON\\Dark.json
          Invoke-WebRequest https://raw.githubusercontent.com/swccgpc/swccg-card-json/main/DarkLegacy.json -Outfile cardlists\\JSON\\DarkLegacy.json
          Invoke-WebRequest https://raw.githubusercontent.com/swccgpc/swccg-card-json/main/Light.json -Outfile cardlists\\JSON\\Light.json
          Invoke-WebRequest https://raw.githubusercontent.com/swccgpc/swccg-card-json/main/LightLegacy.json -Outfile cardlists\\JSON\\LightLegacy.json
          Invoke-WebRequest https://raw.githubusercontent.com/swccgpc/swccg-card-json/main/sets.json -Outfile cardlists\\JSON\\sets.json

      - name: Build DotNET48
        run: |
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\SWListMaker

      - name: Build Cardlists
        run: |
          cd $Env:GITHUB_WORKSPACE\SWListMaker
          bin\\Debug\\SWListMaker.exe

